### ISSUE TITLE
데이터베이스 타입 및 명칭 수정요청

### ISSUE THREAD

**Issue by HaechangLee** [HaechangLee/SE_project03#1]
price_info 테이블의 price 컬럼을 opening_price로 바꾸고, 설계상에 있던 lower_limit_price 컬럼 추가해주셨으면합니다.
또한 Coin테이블의 심볼명이 4자리보다 긴 경우가 있어 이를 담을수 있도록 타입변경해주셨으면 합니다.

**Comment by ns0416** [comment]
이슈 #2 리뷰부탁드립니다
